// Inline closed-form D_pq^EK for p, q in {0..2} (momwire#249).
// Generated by scripts/derive_bspline_static_moments.py (do not edit).
// NOT included from _accelerators.cpp yet — the C++ extended-kernel
// twins are momwire#249 follow-up B; this is the reference they need.
#pragma once
#include <cmath>
#include "_bspline_static_moments_inline.h"

static inline double D_ek_pq_0_0(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*(std::pow(std::pow(a, 2) + std::pow(-B + beta, 2), -1.0/2.0) - 1/std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2)) - 1/std::sqrt(std::pow(a, 2) + std::pow(-A + beta, 2)) + std::pow(std::pow(a, 2) + std::pow(-A + alpha, 2), -1.0/2.0));
}

static inline double D_ek_pq_0_1(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*((A - B)*(-1/std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)) + std::pow(std::pow(a, 2) + std::pow(-B + alpha, 2), -1.0/2.0)) + std::asinh((-A + alpha)/a) - std::asinh((-A + beta)/a) - std::asinh((-B + alpha)/a) + std::asinh((-B + beta)/a));
}

static inline double D_ek_pq_0_2(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*(-2*J_static_pq_0_0(alpha, beta, A, B, a) + (-2*A + 2*B)*(-std::asinh((-B + alpha)/a) + std::asinh((-B + beta)/a)) - std::pow(-A + B, 2)*(-1/std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)) + std::pow(std::pow(a, 2) + std::pow(-B + alpha, 2), -1.0/2.0)));
}

static inline double D_ek_pq_1_0(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*(-std::asinh((-A + alpha)/a) + std::asinh((-B + alpha)/a) - (alpha - beta + std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))*std::asinh((-B + beta)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)) + (alpha - beta + std::sqrt(std::pow(a, 2) + std::pow(-A + beta, 2))*std::asinh((-A + beta)/a))/std::sqrt(std::pow(a, 2) + std::pow(-A + beta, 2)));
}

static inline double D_ek_pq_1_1(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*((A - B)*(-std::asinh((-B + alpha)/a) + (alpha - beta + std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))*std::asinh((-B + beta)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))) + (A - alpha)*std::asinh((-A + alpha)/a) - (A - alpha)*std::asinh((-A + beta)/a) - (B - alpha)*std::asinh((-B + alpha)/a) + (B - alpha)*std::asinh((-B + beta)/a) + std::sqrt(std::pow(a, 2) + std::pow(-A + alpha, 2)) - std::sqrt(std::pow(a, 2) + std::pow(-A + beta, 2)) - std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2)) + std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)));
}

static inline double D_ek_pq_1_2(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*(-2*J_static_pq_1_0(alpha, beta, A, B, a) + (-2*A + 2*B)*(-(B - alpha)*std::asinh((-B + alpha)/a) + (B - alpha)*std::asinh((-B + beta)/a) - std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2)) + std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))) - std::pow(-A + B, 2)*(-std::asinh((-B + alpha)/a) + (alpha - beta + std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))*std::asinh((-B + beta)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))));
}

static inline double D_ek_pq_2_0(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*(-(2*std::pow(a, 2) + std::pow(-B + beta, 2) - 2*(-B + beta)*(B - alpha) - std::pow(B - alpha, 2) + 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))*std::asinh((-B + beta)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)) + (2*std::pow(a, 2) + std::pow(-B + alpha, 2) - 2*(-B + alpha)*(B - alpha) - std::pow(B - alpha, 2) + 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2))*std::asinh((-B + alpha)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2)) + (2*std::pow(a, 2) + std::pow(-A + beta, 2) - 2*(-A + beta)*(A - alpha) - std::pow(A - alpha, 2) + 2*(A - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-A + beta, 2))*std::asinh((-A + beta)/a))/std::sqrt(std::pow(a, 2) + std::pow(-A + beta, 2)) - (2*std::pow(a, 2) + std::pow(-A + alpha, 2) - 2*(-A + alpha)*(A - alpha) - std::pow(A - alpha, 2) + 2*(A - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-A + alpha, 2))*std::asinh((-A + alpha)/a))/std::sqrt(std::pow(a, 2) + std::pow(-A + alpha, 2)));
}

static inline double D_ek_pq_2_1(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*(-1.0/2.0*std::pow(a, 2)*std::asinh((-A + alpha)/a) + (1.0/2.0)*std::pow(a, 2)*std::asinh((-A + beta)/a) + (1.0/2.0)*std::pow(a, 2)*std::asinh((-B + alpha)/a) - 1.0/2.0*std::pow(a, 2)*std::asinh((-B + beta)/a) + (1.0/2.0)*(-A + alpha)*std::sqrt(std::pow(a, 2) + std::pow(-A + alpha, 2)) - 1.0/2.0*(-A + beta)*std::sqrt(std::pow(a, 2) + std::pow(-A + beta, 2)) + (A - B)*((2*std::pow(a, 2) + std::pow(-B + beta, 2) - 2*(-B + beta)*(B - alpha) - std::pow(B - alpha, 2) + 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))*std::asinh((-B + beta)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)) - (2*std::pow(a, 2) + std::pow(-B + alpha, 2) - 2*(-B + alpha)*(B - alpha) - std::pow(B - alpha, 2) + 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2))*std::asinh((-B + alpha)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2))) + std::pow(A - alpha, 2)*std::asinh((-A + alpha)/a) - std::pow(A - alpha, 2)*std::asinh((-A + beta)/a) + 2*(A - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-A + alpha, 2)) - 2*(A - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-A + beta, 2)) - 1.0/2.0*(-B + alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2)) + (1.0/2.0)*(-B + beta)*std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)) - std::pow(B - alpha, 2)*std::asinh((-B + alpha)/a) + std::pow(B - alpha, 2)*std::asinh((-B + beta)/a) - 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2)) + 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)));
}

static inline double D_ek_pq_2_2(double alpha, double beta, double A, double B, double a) {
    return (1.0/4.0)*std::pow(a, 2)*(-2*J_static_pq_2_0(alpha, beta, A, B, a) + (-2*A + 2*B)*((1.0/2.0)*std::pow(a, 2)*std::asinh((-B + alpha)/a) - 1.0/2.0*std::pow(a, 2)*std::asinh((-B + beta)/a) - 1.0/2.0*(-B + alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2)) + (1.0/2.0)*(-B + beta)*std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)) - std::pow(B - alpha, 2)*std::asinh((-B + alpha)/a) + std::pow(B - alpha, 2)*std::asinh((-B + beta)/a) - 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2)) + 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))) - std::pow(-A + B, 2)*((2*std::pow(a, 2) + std::pow(-B + beta, 2) - 2*(-B + beta)*(B - alpha) - std::pow(B - alpha, 2) + 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2))*std::asinh((-B + beta)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + beta, 2)) - (2*std::pow(a, 2) + std::pow(-B + alpha, 2) - 2*(-B + alpha)*(B - alpha) - std::pow(B - alpha, 2) + 2*(B - alpha)*std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2))*std::asinh((-B + alpha)/a))/std::sqrt(std::pow(a, 2) + std::pow(-B + alpha, 2))));
}
