"""NEC-5 printed impedances for the momwire#935 shape-check deck.

GENERATED by scripts/capture_grazing_shape_nec5.py -- do not edit by
hand. See that script for the cards, the depth/theta table and why the
oracle is laddered rather than read once.

Citation: NEC-5 (LLNL-CODE-746721), 5.9114 m centre-fed dipole buried
0.5 / 1 / 3 mm in eps_r 13 / sigma 0.005 S/m soil at 7.1 MHz, uniform
mesh refined x1/x2/x4/x8, 2026-09-06.

`LADDER[depth_mm]` is the four printed impedances in refinement order;
`CONVERGED[depth_mm]` is the first-order Richardson limit and
`BAR[depth_mm]` the gap between it and the x8 print -- the oracle's own
error bar, which is what the gate's tolerance is set from.

No momwire float is recorded here on purpose: the momwire side is
recomputed at test time.
"""

LADDER = {
    0.5: [(176.21 - 6.6189j), (176 - 6.5627j), (175.84 - 6.5648j), (175.69 - 6.6174j)],
    1.0: [
        (172.02 - 0.35762j),
        (171.8 - 0.33665j),
        (171.63 - 0.37027j),
        (171.46 - 0.45284j),
    ],
    3.0: [(165.04 + 10.363j), (164.84 + 10.32j), (164.69 + 10.26j), (164.56 + 10.17j)],
}

CONVERGED = {
    0.5: (175.54 - 6.67j),
    1.0: (171.29000000000002 - 0.53541j),
    3.0: (164.43 + 10.08j),
}

BAR = {
    0.5: 0.15895521381823782,
    1.0: 0.18899154716546387,
    3.0: 0.15811388300841514,
}
