"""NEC-5 printed impedances for the two momwire#567 ANCHOR decks —
the contact-plus-buried serve gates banked while the deck class
refuses (momwire#553 U5, gated at G-U5-12 and the deck route).

GENERATED by scripts/capture_buried_anchor_nec5.py — do not edit by
hand. See that script for the cards, the run recipe and the fan
re-bank story (the pre-phase-0 fan number was a transcription
0.67 ohm off the engine's own printout). Citation: NEC-5
(LLNL-CODE-746721), 10 m contact monopole over detached buried
radials, eps_r 13 / sigma 0.005 S/m, 7 MHz, 2026-08-26.

`ANCHOR_DECKS[name]` is the card text the binary ran, verbatim;
`ANCHOR_LONE_RADIAL` / `ANCHOR_FOUR_RADIAL` are the impedances it
PRINTED for them. The refusal prose in `_medium_spec` and
`eznec/_serve` quotes these numbers; `test_buried_serve_553`'s
G-U5-12 ties the spellings together and scores the decks the day
the refusal lifts.

No momwire float is recorded here on purpose: the momwire side is
recomputed at test time. Pinning it would pin a cross-build float
equality this tree does not have.
"""

ANCHOR_DECKS = {
    "lone-radial": (
        "CM momwire#567 anchor lone-radial\n"
        "CE\n"
        "GW 1,15,0.,0.,10.,0.,0.,0.,.001\n"
        "GW 2,10,0.,0.,-0.15,5.,0.,-0.15,.001\n"
        "GE 1,-1\n"
        "FR 0,1,0,0,7.\n"
        "GN 0,0,0,0,13.,.005\n"
        "EX 4,1,7,0,1.,0.\n"
        "PQ 0\n"
        "XQ 0\n"
        "EN\n"
    ),
    "four-radial": (
        "CM momwire#567 anchor four-radial\n"
        "CE\n"
        "GW 1,15,0.,0.,10.,0.,0.,0.,.001\n"
        "GW 2,10,0.,0.,-0.15,5.,0.,-0.15,.001\n"
        "GW 3,10,0.,0.,-0.15,0.,5.,-0.15,.001\n"
        "GW 4,10,0.,0.,-0.15,-5.,0.,-0.15,.001\n"
        "GW 5,10,0.,0.,-0.15,0.,-5.,-0.15,.001\n"
        "GE 1,-1\n"
        "FR 0,1,0,0,7.\n"
        "GN 0,0,0,0,13.,.005\n"
        "EX 4,1,7,0,1.,0.\n"
        "PQ 0\n"
        "XQ 0\n"
        "EN\n"
    ),
}

ANCHOR_LONE_RADIAL = 92.1300 - 70.1410j
ANCHOR_FOUR_RADIAL = 90.0510 - 70.7310j

# The momwire#524 crossing refinement ladder, FOR THE RECORD ONLY:
# the engine's crossing junction was adjudicated 2026-08-26 as two
# contact ends plus a point-electrode sink (its printed junction
# currents violate its own AGARD condition divergently along this
# ladder), so these prints are a different experiment from the
# exact-EM crossing serve (soil-A answer 138.77 - 102.99j,
# test_crossing_serve_524). NEVER gate the crossing serve on them.
CROSSING_ENGINE_PRINTS = {
    "crossing-x1": 74.7610 - 57.7300j,
    "crossing-x2": 69.1090 - 50.8330j,
    "crossing-x3": 70.8580 - 51.6780j,
    "crossing-x4": 69.0170 - 50.0150j,
    "crossing-x5": 70.0380 - 50.7170j,
    "crossing-x8": 68.8820 - 49.7330j,
}
