"""NEC-5 printed impedances for the two momwire#567 ANCHOR decks —
the contact-plus-buried serve gates banked while the deck class
refuses (momwire#553 U5, gated at G-U5-12 and the deck route).

GENERATED by scripts/capture_buried_anchor_nec5.py — do not edit by
hand. See that script for the cards, the run recipe and the fan
re-bank story (the pre-phase-0 fan number was a transcription
0.67 ohm off the engine's own printout). Citation: NEC-5
(LLNL-CODE-746721), 10 m contact monopole over detached buried
radials, eps_r 13 / sigma 0.005 S/m, 7 MHz, 2026-08-26.

`ANCHOR_DECKS[name]` is the card text the binary ran, verbatim;
`ANCHOR_LONE_RADIAL` / `ANCHOR_FOUR_RADIAL` are the impedances it
PRINTED for them. The refusal prose in `_medium_spec` and
`eznec/_serve` quotes these numbers; `test_buried_serve_553`'s
G-U5-12 ties the spellings together and scores the decks the day
the refusal lifts.

No momwire float is recorded here on purpose: the momwire side is
recomputed at test time. Pinning it would pin a cross-build float
equality this tree does not have.
"""

ANCHOR_DECKS = {
    "lone-radial": (
        "CM momwire#567 anchor lone-radial\n"
        "CE\n"
        "GW 1,15,0.,0.,10.,0.,0.,0.,.001\n"
        "GW 2,10,0.,0.,-0.15,5.,0.,-0.15,.001\n"
        "GE 1,-1\n"
        "FR 0,1,0,0,7.\n"
        "GN 0,0,0,0,13.,.005\n"
        "EX 4,1,7,0,1.,0.\n"
        "PQ 0\n"
        "XQ 0\n"
        "EN\n"
    ),
    "four-radial": (
        "CM momwire#567 anchor four-radial\n"
        "CE\n"
        "GW 1,15,0.,0.,10.,0.,0.,0.,.001\n"
        "GW 2,10,0.,0.,-0.15,5.,0.,-0.15,.001\n"
        "GW 3,10,0.,0.,-0.15,0.,5.,-0.15,.001\n"
        "GW 4,10,0.,0.,-0.15,-5.,0.,-0.15,.001\n"
        "GW 5,10,0.,0.,-0.15,0.,-5.,-0.15,.001\n"
        "GE 1,-1\n"
        "FR 0,1,0,0,7.\n"
        "GN 0,0,0,0,13.,.005\n"
        "EX 4,1,7,0,1.,0.\n"
        "PQ 0\n"
        "XQ 0\n"
        "EN\n"
    ),
}

ANCHOR_LONE_RADIAL = 92.1300 - 70.1410j
ANCHOR_FOUR_RADIAL = 90.0510 - 70.7310j

# THESE TWO ARE NOT "WHAT THE ENGINE ANSWERS" (momwire#929).
#
# Both anchors stand a monopole's lower END in the plane with detached radials
# below it and nothing continuing under the node, and both carry `GE 1,-1` —
# ground flag 1 with the segment-check field at -1. antennaknobs#1025 found the
# wrapper that wrote those cards had the two fields transposed. Flag 1 is
# documented as not usable when wires go below the surface; the flag that IS
# usable leaves the current expansion alone, which gives a wire ending at z=0
# no basis function there, so the same decks read 25.9420 - 968.5600j and
# 25.2270 - 967.9100j under it — an open-circuited monopole, a 93 % change.
#
# So this geometry has no documented spelling at all: one flag is excluded by
# the burial, the other cannot feed a conductor that stops on the interface
# (antennaknobs#925). The numbers above are faithful captures — they reproduce
# to the digit, which the re-capture script checks before it writes anything —
# but they are prints of a combination the engine does not document, and must
# not be cited as the licensed engine's answer for this class, in refusal prose
# or anywhere else.
#
# The CONNECTED spelling is the one with an answer. A rise from the buried hub
# up to the node continues the conductor through the interface, and under the
# documented card that deck agrees with momwire to 2.6 % in R at four radials
# and 3.9 % at twelve (antennaknobs#1025). Verified against our licensed
# materials; conclusions only.
#
# The convention note this replaced said momwire's connected fan and the
# engine's detached stake were "a documented convention difference, never a
# parity target in either direction". The first half stands — they are
# different physical decks. The second half was measured against a print that
# had no valid spelling behind it.

# The momwire#524 crossing refinement ladder, FOR THE RECORD ONLY:
# the engine's crossing junction was adjudicated 2026-08-26 as two
# contact ends plus a point-electrode sink (its printed junction
# currents violate its own AGARD condition divergently along this
# ladder), so these prints are a different experiment from the
# exact-EM crossing serve (soil-A answer 138.77 - 102.99j,
# test_crossing_serve_524). NEVER gate the crossing serve on them.
CROSSING_ENGINE_PRINTS = {
    "crossing-x1": 74.7610 - 57.7300j,
    "crossing-x2": 69.1090 - 50.8330j,
    "crossing-x3": 70.8580 - 51.6780j,
    "crossing-x4": 69.0170 - 50.0150j,
    "crossing-x5": 70.0380 - 50.7170j,
    "crossing-x8": 68.8820 - 49.7330j,
}
