"""NEC-5 printed impedances for GROUND-CONTACT decks over the
binary's native Sommerfeld ground, and over PEC.

GENERATED by scripts/capture_contact_nec5_lane.py — do not edit by
hand. See that script for the decks, the dimensions, the run recipe
and the two bar shapes these numbers are gated against
(momwire#282 stage 1). Citation: NEC-5 (LLNL-CODE-746721),
ground-contact ladder decks over four soils, 2026-08-18.

`CONTACT_LADDERS[geometry][ground]` is a tuple of `(N_total, Z)`,
the impedance the binary PRINTED for that deck at that mesh. The
`pec` row of each geometry is the control the ground-induced shift
`delta = Z(ground) - Z(pec)` is taken against, at matched N — the
difference of columns that cancels the formulation's own offset and
leaves the ground.

`GROUND_EPS` is the (eps_r, sigma) the corresponding `GN 0` card
carried, so a consumer builds the momwire side from the same
constants rather than a transcription of them.

No momwire float is recorded here on purpose: the momwire column is
recomputed at test time. Pinning it would pin a cross-build float
equality this tree does not have.
"""

GROUND_EPS = {
    "sea": (81.0, 5.0),
    "vgood": (20.0, 0.0303),
    "avg": (13.0, 0.005),
    "poor": (5.0, 0.001),
}

CONTACT_LADDERS = {
    "monopole": {
        "pec": (
            (11, 39.8820 + 19.2600j),
            (21, 40.3790 + 21.0870j),
            (41, 40.6430 + 22.0180j),
            (61, 40.7450 + 22.3610j),
            (81, 40.8040 + 22.5510j),
        ),
        "sea": (
            (11, 41.8430 + 20.3150j),
            (21, 42.5050 + 22.4220j),
            (41, 42.8580 + 23.5730j),
            (61, 42.9880 + 24.0100j),
            (81, 43.0590 + 24.2500j),
        ),
        "vgood": (
            (11, 51.9360 + 22.2610j),
            (21, 52.6620 + 24.6770j),
            (41, 53.0310 + 25.9260j),
            (61, 53.1700 + 26.3760j),
            (81, 53.2480 + 26.6160j),
        ),
        "avg": (
            (11, 51.2860 + 19.2070j),
            (21, 52.0060 + 21.5050j),
            (41, 52.3720 + 22.6850j),
            (61, 52.5080 + 23.1100j),
            (81, 52.5840 + 23.3380j),
        ),
        "poor": (
            (11, 43.5710 + 15.1130j),
            (21, 44.2440 + 17.1690j),
            (41, 44.5870 + 18.2220j),
            (61, 44.7130 + 18.6070j),
            (81, 44.7830 + 18.8170j),
        ),
    },
    "invl": {
        "pec": (
            (12, 20.5800 - 2.3661j),
            (24, 20.6670 - 1.4983j),
            (48, 20.7050 - 1.0642j),
            (72, 20.7190 - 0.8870j),
            (96, 20.7280 - 0.7808j),
        ),
        "sea": (
            (12, 22.3800 - 1.0755j),
            (24, 22.6190 + 0.0844j),
            (48, 22.7290 + 0.7304j),
            (72, 22.7630 + 0.9922j),
            (96, 22.7800 + 1.1431j),
        ),
        "vgood": (
            (12, 31.9490 + 2.8396j),
            (24, 32.2060 + 4.3185j),
            (48, 32.3160 + 5.0609j),
            (72, 32.3540 + 5.3389j),
            (96, 32.3750 + 5.4939j),
        ),
        "avg": (
            (12, 31.9940 + 0.0430j),
            (24, 32.2640 + 1.4159j),
            (48, 32.3850 + 2.0979j),
            (72, 32.4270 + 2.3550j),
            (96, 32.4500 + 2.4995j),
        ),
        "poor": (
            (12, 25.1400 - 5.2615j),
            (24, 25.4060 - 4.1377j),
            (48, 25.5300 - 3.5796j),
            (72, 25.5740 - 3.3621j),
            (96, 25.5980 - 3.2363j),
        ),
    },
}
