"""NEC-5 printed impedances for GROUNDED (contact) decks, and the
razor lanes.

GENERATED by scripts/capture_razor_contact_nec5_lane.py — do not edit
by hand. See that script for the decks, the dimensions, the run recipe
and the sharp-lane bar these numbers are gated against (momwire#398
unit 3). Citation: NEC-5 (LLNL-CODE-746721), ground-contact ladder
decks, 2026-08-17.

Each row is (N_total, Z_nec5_contact, Z_nec5_mirror_half,
Z_razor_n5q, Z_razor_gl):

  Z_nec5_contact      the binary on the GROUNDED deck (GE 1 + GN 1),
                      N segments, driven at the base
  Z_nec5_mirror_half  the binary on the same radiator PLUS ITS IMAGE
                      in free space, 2N segments, centre-driven, and
                      halved — the same antenna by image theory, and
                      the deck razor's grounded-end basis reproduces
  Z_razor_n5q         `RazorSolver(ground_z=0, feed_arclength=0,
                      nec5_quadrature=True)`
  Z_razor_gl          the same on the default Gauss-Legendre path
                      quadrature

Only Z_razor_n5q against Z_nec5_mirror_half is GATED. Against
Z_nec5_contact the residual decays with N rather than holding
constant, because NEC-5's grounded deck is not NEC-5's own mirror
deck halved either; the capture script's docstring has the numbers
and the reading. The GL column is recorded so the deferred
production-lane bar has a starting point on file.
"""

CONTACT_LADDERS = {
    "monopole": (
        (
            24,
            39.2000 + 20.8410j,
            39.33300 + 20.55600j,
            39.335168 + 20.574633j,
            39.354331 + 20.749674j,
        ),
        (
            32,
            39.2620 + 21.1500j,
            39.41100 + 20.94200j,
            39.413364 + 20.960694j,
            39.424097 + 21.057783j,
        ),
        (
            48,
            39.3500 + 21.4570j,
            39.48800 + 21.31900j,
            39.490234 + 21.337880j,
            39.494963 + 21.380157j,
        ),
        (
            64,
            39.4050 + 21.6140j,
            39.52700 + 21.50950j,
            39.529369 + 21.528294j,
            39.532010 + 21.551722j,
        ),
        (
            96,
            39.4710 + 21.7810j,
            39.56800 + 21.70750j,
            39.570553 + 21.726362j,
            39.571713 + 21.736552j,
        ),
    ),
    "invl": (
        (
            24,
            20.6260 - 2.3666j,
            20.52450 - 2.43080j,
            20.525503 - 2.412200j,
            20.498130 - 2.950226j,
        ),
        (
            32,
            20.5990 - 2.1930j,
            20.53850 - 2.24760j,
            20.539475 - 2.228974j,
            20.518106 - 2.661440j,
        ),
        (
            48,
            20.5810 - 2.0283j,
            20.55100 - 2.07015j,
            20.552066 - 2.051428j,
            20.537326 - 2.357155j,
        ),
        (
            64,
            20.5760 - 1.9443j,
            20.55700 - 1.97855j,
            20.558090 - 1.959768j,
            20.546899 - 2.194326j,
        ),
        (
            96,
            20.5730 - 1.8532j,
            20.56300 - 1.87880j,
            20.564245 - 1.859890j,
            20.556760 - 2.018197j,
        ),
    ),
}
