"""NEC-5 printed impedances over a PEC ground, and the razor lanes.

GENERATED by scripts/capture_razor_pec_nec5_lane.py — do not edit by
hand. See that script for the decks, the heights, the run recipe and
the sharp-lane bar these numbers are gated against (momwire#398 unit
2). Citation: NEC-5 (LLNL-CODE-746721), PEC-ground ladder decks,
2026-08-17.

Each row is (N_total, Z_nec5, Z_razor_n5q, Z_razor_gl): the binary's
printed impedance, `RazorSolver(ground_z=0, nec5_quadrature=True)`,
and `RazorSolver(ground_z=0)` on its default Gauss-Legendre path
quadrature. Only the n5q column is gated (the GL / production bar is
deferred with the finite grounds); the GL column is recorded so the
deferred bar's starting point is on the record.
"""

PEC_LADDERS = {
    "dipole": (
        (24, 75.5450 - 3.6721j, 75.551235 - 3.634735j, 75.665371 - 2.305583j),
        (32, 75.8630 - 1.9062j, 75.868654 - 1.868728j, 75.933000 - 1.130639j),
        (48, 76.1490 - 0.3053j, 76.154872 - 0.267723j, 76.183381 + 0.054042j),
        (64, 76.2820 + 0.4490j, 76.288574 + 0.486632j, 76.304528 + 0.665055j),
        (96, 76.4130 + 1.1914j, 76.419058 + 1.229177j, 76.426078 + 1.306846j),
    ),
    "fat-dipole": (
        (24, 79.3420 + 18.8490j, 79.350784 + 18.883540j, 79.480198 + 19.795563j),
        (32, 79.8580 + 20.6110j, 79.867656 + 20.648708j, 79.940780 + 21.152054j),
        (48, 80.3770 + 22.3450j, 80.389316 + 22.391031j, 80.421783 + 22.608547j),
        (64, 80.6510 + 23.2380j, 80.666511 + 23.292354j, 80.684704 + 23.412258j),
        (96, 80.9540 + 24.1910j, 80.976400 + 24.265324j, 80.984427 + 24.317148j),
    ),
    "invvee": (
        (24, 52.4390 - 0.7403j, 52.441118 - 0.704856j, 52.513528 - 2.051980j),
        (32, 52.6740 + 0.2949j, 52.676145 + 0.330401j, 52.717598 - 0.939651j),
        (48, 52.8880 + 1.1610j, 52.890367 + 1.196574j, 52.909130 + 0.182062j),
        (64, 52.9890 + 1.5456j, 52.991355 + 1.581211j, 53.002020 + 0.760599j),
        (96, 53.0880 + 1.9158j, 53.090529 + 1.951482j, 53.095335 + 1.368149j),
    ),
    "loop": (
        (24, 205.4700 + 260.1200j, 205.492673 + 260.186319j, 205.082733 + 258.384977j),
        (32, 208.2800 + 265.1000j, 208.306672 + 265.167257j, 207.453452 + 261.084823j),
        (48, 210.4000 + 267.4900j, 210.424308 + 267.559535j, 209.471267 + 263.041723j),
        (64, 211.2100 + 267.7200j, 211.231478 + 267.792405j, 210.370442 + 263.750692j),
        (96, 211.8800 + 267.3300j, 211.900235 + 267.400310j, 211.230491 + 264.292291j),
    ),
}
