"""The rectangular same-edge window (momwire#968), #966's other half.

#967 chunked the same-edge correction over observer rows but left `A_st` and
`A_reg` whole-edge, because the C++ reg kernel validated `R.shape ==
(N*n_qp, N*n_qp)` and refused a rectangular window. Those two were most of the
3.9 GB that remained on a 4,001-segment single wire.

The kernel never actually needed square: its observer (`i`) and source (`j`)
axes were independent throughout — `wu(p,i,q)` on one side, `wu(P,j,r)` on the
other. So the generalisation is a separate row-side and column-side `wu_pow`,
with the square entry point passing one array twice and executing the identical
instruction stream. The static block is Toeplitz, so its window is a GATHER of
the same 2N-1 table.

Gates:

- G-968-1  every window equals the square answer's sub-block EXACTLY, across
           degrees, n_qp, EK on/off, accelerator on/off, and edge windows —
           including the degenerate empty and full-height ones.
- G-968-2  the square C++ entry points still answer what they answered before
           the change. Banked from a pre-change build and compared after
           rebuilding, not reasoned about (the momwire#762 protocol).
- G-968-3  chunked == dense bit-identically on ordinary decks and within the
           reassociation bound on the long wire — #967's statement, unmoved.
- G-968-4  the windowed route is what a default solve takes, counted at the
           producer, and the memory it saves is real: tracemalloc-peak RATIO
           between arms, one process each.
- G-968-5  the Toeplitz table is memoised across a window loop, because
           rebuilding it per window measured 3.7x slower across an edge than
           the single square call.

The oracle for G-968-2 is regenerated by `scripts/bank_same_edge_oracle.py`
against a build of the PREVIOUS commit; it is committed as a fixture so the
gate does not need two builds to run.
"""

import itertools
import subprocess
import sys
import textwrap
from pathlib import Path

import numpy as np
import pytest

import momwire._bspline_kernels as bk
import momwire.bspline as _bs
from momwire._accel import acc as _acc
from momwire._bspline_kernels import (
    _EK,
    _seg_seg_reg_geometry,
    _seg_seg_reg_moments_from_geometry,
    _seg_seg_static_moments,
    _static_toeplitz_table,
)
from momwire.bspline import BSplineSolver

_ORACLE = Path(__file__).with_name("data") / "same_edge_oracle_968.npz"
C0 = 299792458.0
LONG_WIRE = [np.array([(0.0, 0.0, 0.0), (0.0, 4000.0, 0.0)])]
LONG_LAM = C0 / 15e6

_ACCEL_FLAGS = (
    "_HAVE_BSPLINE_REG_SWEPT_ACCEL",
    "_HAVE_BSPLINE_REG_SWEPT_EK_ACCEL",
    "_HAVE_BSPLINE_STATIC_ACCEL",
    "_HAVE_BSPLINE_STATIC_EK_ACCEL",
)


# ---------------------------------------------------------------------
# G-968-1: a window IS the sub-block
# ---------------------------------------------------------------------


@pytest.mark.parametrize("accel", [True, False], ids=["accel", "numpy"])
@pytest.mark.parametrize("ek_on", [False, True], ids=["reduced", "ek"])
@pytest.mark.parametrize("n_qp", [2, 4])
@pytest.mark.parametrize("max_d", [1, 2])
@pytest.mark.parametrize("N", [7, 12])
def test_every_window_equals_the_square_sub_block(
    N, max_d, n_qp, ek_on, accel, monkeypatch
):
    """Exactly, not approximately, on every route.

    The numpy arm is not decoration: the accelerator is absent on some
    platforms, and a windowed numpy einsum that transposed its two `wu`
    operands would still look plausible and be wrong on every off-diagonal
    block.
    """
    if not accel:
        for flag in _ACCEL_FLAGS:
            monkeypatch.setattr(bk, flag, False)
    h = 0.37
    seg = np.arange(N + 1) * h
    a = 5e-4
    ek = _EK(a=1.7e-3, group_i=None, group_j=None) if ek_on else None
    full_reg = _seg_seg_reg_moments_from_geometry(
        _seg_seg_reg_geometry(seg, a, max_d, n_qp, ek=ek), 0.77
    )
    full_st = _seg_seg_static_moments(seg, a, max_d, ek=ek)
    # Full height, one row, an interior run, the last rows, and EMPTY — the
    # last because a chunk loop can hand over a zero-width window at the end
    # of an edge and a silent shape error there would be a wrong answer, not
    # a crash.
    for r0, r1 in ((0, N), (0, 1), (2, 5), (N - 2, N), (3, 3)):
        win = slice(r0, r1)
        got_reg = _seg_seg_reg_moments_from_geometry(
            _seg_seg_reg_geometry(seg, a, max_d, n_qp, ek=ek, rows=win), 0.77
        )
        got_st = _seg_seg_static_moments(seg, a, max_d, ek=ek, rows=win)
        assert np.array_equal(got_reg, full_reg[:, :, r0:r1, :]), (r0, r1, "reg")
        assert np.array_equal(got_st, full_st[:, :, r0:r1, :]), (r0, r1, "static")


def test_a_window_is_not_secretly_the_transpose():
    """The one failure a sub-block comparison on a SYMMETRIC block would miss.

    A same-edge reg block is not symmetric in general, but it is close enough
    that a swapped row/column `wu` would still pass a loose tolerance. This
    asserts the block genuinely differs from its own transpose, so the
    equality above is testing what it claims.
    """
    h, a, N, max_d, n_qp = 0.37, 5e-4, 9, 2, 4
    seg = np.arange(N + 1) * h
    full = _seg_seg_reg_moments_from_geometry(
        _seg_seg_reg_geometry(seg, a, max_d, n_qp), 0.77
    )
    # p/P are the polynomial axes; i/j the segment axes. Swapping the segment
    # axes alone must change the block.
    assert not np.array_equal(full, np.swapaxes(full, 2, 3))


# ---------------------------------------------------------------------
# G-968-2: the square entry points did not move
# ---------------------------------------------------------------------


@pytest.mark.skipif(not _ORACLE.exists(), reason="oracle fixture not banked")
def test_the_square_entry_points_are_bit_identical_to_the_pre_change_build():
    """The #762 protocol: banked from a build of the previous commit, compared
    after rebuilding. Not a diff read.

    This caught a real one. The first spelling wrote the closed-form Toeplitz
    loop out twice — once in the square impl, once in the new table producer —
    and with two copies in the translation unit GCC inlined
    `J_static_dispatch` differently in each, moving the square answer by
    5.3e-15 relative on a handful of entries. Nothing about the algebra
    changed; the schedule did. The square impl now CALLS the producer, so
    there is one copy and nothing to schedule two ways.
    """
    banked = np.load(_ORACLE)
    checked = 0
    for N, max_d, n_qp in itertools.product((3, 7, 12), (1, 2), (2, 4)):
        h, a = 0.37, 5e-4
        geo = _seg_seg_reg_geometry(np.arange(N + 1) * h, a, max_d, n_qp)
        R = np.ascontiguousarray(geo["R"], dtype=np.float64)
        wu = np.ascontiguousarray(geo["wu_pow"], dtype=np.float64)
        ks = np.ascontiguousarray(np.array([0.31, 0.77, 1.9], dtype=np.float64))
        pairs = {
            f"reg/{N}/{max_d}/{n_qp}": _acc.seg_seg_reg_moments_bspline_swept(
                R, wu, ks
            ),
            f"regek/{N}/{max_d}/{n_qp}": _acc.seg_seg_reg_moments_bspline_swept_ek(
                R, wu, ks, 1.7e-3
            ),
            f"stat/{N}/{max_d}": _acc.seg_seg_static_moments_bspline_uniform(
                h, a, N, max_d
            ),
            f"statek/{N}/{max_d}": _acc.seg_seg_static_moments_bspline_uniform_ek(
                h, a, N, max_d, 1.7e-3
            ),
        }
        for key, got in pairs.items():
            assert np.array_equal(got, banked[key]), key
            checked += 1
    assert checked == 48, checked


# ---------------------------------------------------------------------
# G-968-3: #967's statement, unmoved
# ---------------------------------------------------------------------

ORDINARY = {
    "dipole": (
        [np.array([(0.0, 0.0, -2.0), (0.0, 0.0, 2.0)])],
        [[40]],
        8.0,
        0.01,
        [(0, 2.0, 1 + 0j)],
    ),
    "invvee": (
        [np.array([(-1.6, 0.0, 0.6), (0.0, 0.0, 1.9), (1.6, 0.0, 0.6)])],
        [[20, 20]],
        8.0,
        0.01,
        [(0, 2.06, 1 + 0j)],
    ),
}


def _solve(wires, nspec, lam, radius, feeds, degree, *, chunked=True, mem=None):
    kw = {} if mem is None else {"swept_mem_mb": mem}
    old = _bs._SAME_EDGE_CORR_CHUNKED
    _bs._SAME_EDGE_CORR_CHUNKED = chunked
    try:
        return complex(
            BSplineSolver(
                wires=wires,
                n_per_edge_per_wire=nspec,
                wavelength=lam,
                wire_radius=radius,
                feeds=feeds,
                degree=degree,
                **kw,
            ).compute_impedance()[0]
        )
    finally:
        _bs._SAME_EDGE_CORR_CHUNKED = old


@pytest.mark.parametrize("degree", [1, 2])
@pytest.mark.parametrize("name", sorted(ORDINARY))
def test_windowing_did_not_disturb_an_ordinary_deck(name, degree):
    """Still bit-identical between routes: an edge that fits one window takes
    one window, and one window of a whole edge is the whole edge."""
    w, n, lam, rad, feeds = ORDINARY[name]
    assert _solve(w, n, lam, rad, feeds, degree, chunked=True) == _solve(
        w, n, lam, rad, feeds, degree, chunked=False
    )


@pytest.mark.parametrize("degree", [1, 2])
def test_the_long_wire_stays_inside_its_reassociation_bound(degree):
    n, mem = 1200, 4
    zc = _solve(
        LONG_WIRE,
        [[n]],
        LONG_LAM,
        5e-6,
        [(0, 2000.0, 1 + 0j)],
        degree,
        chunked=True,
        mem=mem,
    )
    zd = _solve(
        LONG_WIRE,
        [[n]],
        LONG_LAM,
        5e-6,
        [(0, 2000.0, 1 + 0j)],
        degree,
        chunked=False,
        mem=mem,
    )
    assert zc == pytest.approx(zd, rel=1e-11), f"{zc!r} vs {zd!r}"


# ---------------------------------------------------------------------
# G-968-4: the default route, and what it saves
# ---------------------------------------------------------------------


def test_a_default_solve_windows_the_static_and_reg_blocks(monkeypatch):
    """Counted at the producers, with nothing in the test touching a switch."""
    rows_seen = []
    real_st = _bs._seg_seg_static_moments
    real_geo = _bs._seg_seg_reg_geometry

    def spy_st(seg, a, max_d, *, ek=None, rows=None):
        rows_seen.append(("static", rows))
        return real_st(seg, a, max_d, ek=ek, rows=rows)

    def spy_geo(seg, a, max_d, n_qp, *, ek=None, rows=None):
        rows_seen.append(("reg", rows))
        return real_geo(seg, a, max_d, n_qp, ek=ek, rows=rows)

    monkeypatch.setattr(_bs, "_seg_seg_static_moments", spy_st)
    monkeypatch.setattr(_bs, "_seg_seg_reg_geometry", spy_geo)
    n, mem = 1200, 4
    BSplineSolver(
        wires=LONG_WIRE,
        n_per_edge_per_wire=[[n]],
        wavelength=LONG_LAM,
        wire_radius=5e-6,
        feeds=[(0, 2000.0, 1 + 0j)],
        degree=2,
        swept_mem_mb=mem,
    ).compute_impedance()
    for kind in ("static", "reg"):
        calls = [r for k, r in rows_seen if k == kind]
        assert len(calls) > 1, f"{kind} was built {len(calls)} time(s), not windowed"
        assert all(r is not None for r in calls), f"{kind} took a whole-edge call"
        assert all(r.stop - r.start < n for r in calls), (
            f"a {kind} window covered the whole {n}-segment edge: {calls}"
        )


def test_the_toeplitz_table_is_memoised_across_a_window_loop():
    """G-968-5. Without this the windowed static path is 3.7x slower across an
    edge than the single square call — the table is the work, the gather is a
    copy."""
    _static_toeplitz_table.cache_clear()
    before = _static_toeplitz_table.cache_info()
    h, a, N, max_d = 0.5, 5e-4, 60, 2
    seg = np.arange(N + 1) * h
    for r0 in range(0, N, 10):
        _seg_seg_static_moments(seg, a, max_d, rows=slice(r0, min(r0 + 10, N)))
    after = _static_toeplitz_table.cache_info()
    assert after.misses - before.misses == 1, (
        f"the table was built {after.misses - before.misses} times for one edge"
    )
    assert after.hits - before.hits == 5, after


# --- the memory ratio, one process per arm (the #967 instrument) ---------
#
# `tracemalloc` peak, never `ru_maxrss`: a forked child inherits its parent's
# high-water mark, which made an absolute RSS gate report 1,610 MB for an arm
# that takes 900 MB alone (momwire#967). Ratios, so the gate measures the
# change and not the box.
#
# Measured on this box at N=1500, d=2, 64 MB budget:
#   windowed (ships)        338 MB
#   whole-edge A_st/A_reg   811 MB    ratio 2.40
_MEM_N, _MEM_DEGREE, _MEM_MEM = 1500, 2, 64
_WHOLE_EDGE_MIN_RATIO = 1.5
_SHIPPED_MAX_MB = 600.0

_ARM = textwrap.dedent(
    """
    import sys, tracemalloc
    import numpy as np
    import momwire.bspline as bs
    bs._SAME_EDGE_WINDOW_BLOCKS = sys.argv[1] == "1"
    tracemalloc.start()
    bs.BSplineSolver(
        wires=[np.array([(0.0, 0.0, 0.0), (0.0, 4000.0, 0.0)])],
        n_per_edge_per_wire=[[%d]],
        wavelength=%r,
        wire_radius=5e-6,
        feeds=[(0, 2000.0, 1 + 0j)],
        degree=%d,
        swept_mem_mb=%d,
    ).compute_impedance()
    print(tracemalloc.get_traced_memory()[1] / 1e6)
    """
) % (_MEM_N, LONG_LAM, _MEM_DEGREE, _MEM_MEM)


def _arm_peak_mb(windowed):
    import os

    env = dict(os.environ)
    env.update(OMP_NUM_THREADS="1", OPENBLAS_NUM_THREADS="1", MKL_NUM_THREADS="1")
    done = subprocess.run(
        [sys.executable, "-c", _ARM, "1" if windowed else "0"],
        capture_output=True,
        text=True,
        env=env,
        cwd=str(Path(__file__).resolve().parents[1]),
    )
    assert done.returncode == 0, done.stderr[-2000:]
    return float(done.stdout.strip().splitlines()[-1])


@pytest.mark.slow
def test_windowing_the_blocks_is_what_saves_the_memory():
    shipped = _arm_peak_mb(True)
    whole = _arm_peak_mb(False)
    assert shipped < _SHIPPED_MAX_MB, f"shipped route traced {shipped:.0f} MB"
    ratio = whole / shipped
    assert ratio > _WHOLE_EDGE_MIN_RATIO, (
        f"building A_st/A_reg whole-edge cost {whole:.0f} MB against the "
        f"windowed {shipped:.0f} MB — a ratio of {ratio:.2f}, under the "
        f"{_WHOLE_EDGE_MIN_RATIO:.2f} this gate needs to tell them apart"
    )


def test_windowing_is_the_default():
    assert _bs._SAME_EDGE_WINDOW_BLOCKS is True
