#!/usr/bin/env python3
"""Crew-size x threads matrix harness for a live SimNEC session (#375).

SimNEC fans decks across a crew of resident portals (``necCrewSize``); each
portal's thread pools are whatever the environment says at spawn.  This
harness prepares one (crew, threads) configuration at a time, instruments
it, and collects the numbers the issue asks for: per-deck latency (via
``portal_bench_shim.py``), sweep wall-time, cache hit rates per process,
and peak RSS.

Subcommands
-----------
setup   --crew N --threads T --run-dir DIR
        Edit the SimNEC preferences (SimNEC must NOT be running: it rewrites
        the file on exit), regenerate the bench wrapper with the env thread
        caps, and create the run dir.  Thread caps are plain environment
        variables in the wrapper -- the pools snapshot their environment at
        library load, so no in-process flag is needed.
sample  --run-dir DIR
        RSS sampler; run in the background for the whole session, SIGTERM to
        stop.  Records portal / shim / SimNEC-JVM resident sums at 2 Hz.
collect --run-dir DIR
        Aggregate the shim logs, cache stats and RSS trace into
        DIR/summary.json and print the config's row.

The wrapper name keeps ``nec2c`` in it and the whole path avoids the
substring ``out`` -- both of SimNEC's filename rules.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import re
import signal
import statistics
import subprocess
import sys
import time
from pathlib import Path

HOME = Path.home()
PREFS = HOME / ".SimNEC" / "5" / "1" / "preferences"
WRAPPER = HOME / "nec-wrappers" / "momwire-nec2c-bench"
REPO_ROOT = Path(__file__).resolve().parent.parent
PORTAL = REPO_ROOT.parent / ".venv" / "bin" / "momwire-nec2c"
SHIM = REPO_ROOT / "scripts" / "portal_bench_shim.py"


def _simnec_running() -> bool:
    return (
        subprocess.run(["pgrep", "-f", "SimNEC.jar"], capture_output=True).returncode
        == 0
    )


def cmd_setup(args: argparse.Namespace) -> int:
    if _simnec_running():
        print(
            "SimNEC is running -- close it first (it rewrites the "
            "preferences file on exit and would clobber this edit).",
            file=sys.stderr,
        )
        return 1
    if "out" in str(WRAPPER):
        print(f"wrapper path {WRAPPER} contains 'out'", file=sys.stderr)
        return 1

    run_dir = args.run_dir.resolve()
    run_dir.mkdir(parents=True, exist_ok=True)

    backup = PREFS.with_suffix(".bak-375")
    if not backup.exists():
        backup.write_bytes(PREFS.read_bytes())
    text = PREFS.read_text()
    text, n_crew = re.subn(
        r"(<n>necCrewSize</n><v>)\d+(</v>)", rf"\g<1>{args.crew}\g<2>", text
    )
    text, n_cmd = re.subn(
        r"(<n>necCommand</n>\s*<v>)[^<]*(</v>)", rf"\g<1>{WRAPPER}\g<2>", text
    )
    if n_crew != 1 or n_cmd != 1:
        print(
            f"preferences edit matched crew={n_crew} cmd={n_cmd} times "
            "(expected 1 each); aborting, file untouched",
            file=sys.stderr,
        )
        return 1
    PREFS.write_text(text)

    WRAPPER.parent.mkdir(exist_ok=True)
    WRAPPER.write_text(f"""#!/bin/sh
# Generated by bench_portal_crew.py -- config crew={args.crew} threads={args.threads}
export OMP_NUM_THREADS={args.threads}
export OPENBLAS_NUM_THREADS={args.threads}
export MKL_NUM_THREADS={args.threads}
for a in "$@"; do
  [ "$(printf %s "$a" | tr -d - | tr "[:upper:]" "[:lower:]")" = "version" ] \\
    && exec "{PORTAL}" "$@"
done
exec "{sys.executable}" "{SHIM}" --log-dir "{run_dir}" -- \\
  "{PORTAL}" --cache --cache-stats "{run_dir}/cache.$$.json" "$@"
""")
    WRAPPER.chmod(0o755)

    (run_dir / "config.json").write_text(
        json.dumps(
            {
                "crew": args.crew,
                "threads": args.threads,
                "date": _dt.datetime.now().isoformat(timespec="seconds"),
                "portal": str(PORTAL),
            },
            indent=1,
        )
    )
    print(f"ready: crew={args.crew} threads={args.threads} -> {run_dir}")
    return 0


def _rss_kb(pid: int) -> int:
    try:
        with open(f"/proc/{pid}/status") as fh:
            for line in fh:
                if line.startswith("VmRSS:"):
                    return int(line.split()[1])
    except OSError:
        pass
    return 0


def _pids_matching(pattern: str) -> list[int]:
    out = subprocess.run(
        ["pgrep", "-f", pattern], capture_output=True, text=True
    ).stdout
    return [int(p) for p in out.split()]


def cmd_sample(args: argparse.Namespace) -> int:
    run_dir = args.run_dir.resolve()
    trace = (run_dir / "rss.jsonl").open("a")
    stop = []
    signal.signal(signal.SIGTERM, lambda *_: stop.append(1))
    while not stop:
        shims = set(_pids_matching("portal_bench_shim"))
        portals = [p for p in _pids_matching("momwire-nec2c") if p not in shims]
        java = _pids_matching("SimNEC.jar")
        trace.write(
            json.dumps(
                {
                    "t": time.time(),
                    "portal_kb": sum(_rss_kb(p) for p in portals),
                    "n_portals": len(portals),
                    "shim_kb": sum(_rss_kb(p) for p in shims),
                    "java_kb": sum(_rss_kb(p) for p in java),
                }
            )
            + "\n"
        )
        trace.flush()
        time.sleep(0.5)
    return 0


def cmd_collect(args: argparse.Namespace) -> int:
    run_dir = args.run_dir.resolve()
    config = json.loads((run_dir / "config.json").read_text())

    decks: list[dict] = []
    per_proc: dict[str, int] = {}
    for f in sorted(run_dir.glob("decks.*.jsonl")):
        rows = [json.loads(l) for l in f.read_text().splitlines()]
        per_proc[f.stem.split(".")[1]] = len(rows)
        decks.extend(rows)
    decks.sort(key=lambda r: r.get("t_in") or 0)
    dts = [r["dt_ms"] for r in decks if r.get("dt_ms") is not None]

    cache = {
        "hits": 0,
        "misses": 0,
        "fills": 0,
        "entries": 0,
        "bytes": 0,
        "decks_rendered": 0,
    }
    for f in run_dir.glob("cache.*.json"):
        st = json.loads(f.read_text())
        for k in cache:
            cache[k] += st.get(k, 0)

    peak = {"portal_kb": 0, "java_kb": 0, "n_portals": 0}
    rss_file = run_dir / "rss.jsonl"
    if rss_file.exists():
        for line in rss_file.read_text().splitlines():
            row = json.loads(line)
            for k in peak:
                peak[k] = max(peak[k], row.get(k, 0))

    summary = {
        "config": config,
        "decks": len(decks),
        "processes_used": len(per_proc),
        "decks_per_process": per_proc,
        "dt_ms": None
        if not dts
        else {
            "median": round(statistics.median(dts), 1),
            "p90": round(statistics.quantiles(dts, n=10)[8], 1)
            if len(dts) >= 10
            else None,
            "max": round(max(dts), 1),
        },
        "span_s": None
        if len(decks) < 2
        else round(decks[-1]["t_out"] - decks[0]["t_in"], 2),
        "cache": cache,
        "peak_rss": peak,
    }
    (run_dir / "summary.json").write_text(json.dumps(summary, indent=1))
    served = cache["decks_rendered"] or 1
    print(
        f"crew={config['crew']:<3} threads={config['threads']:<2} "
        f"decks={len(decks):<4} procs={len(per_proc):<3} "
        f"med={summary['dt_ms'] and summary['dt_ms']['median']}ms "
        f"p90={summary['dt_ms'] and summary['dt_ms']['p90']}ms "
        f"span={summary['span_s']}s "
        f"hit={cache['hits']}/{served} "
        f"peakRSS={peak['portal_kb'] // 1024}MB x{peak['n_portals']}"
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("setup")
    p.add_argument("--crew", type=int, required=True)
    p.add_argument("--threads", type=int, required=True)
    p.add_argument("--run-dir", type=Path, required=True)
    p = sub.add_parser("sample")
    p.add_argument("--run-dir", type=Path, required=True)
    p = sub.add_parser("collect")
    p.add_argument("--run-dir", type=Path, required=True)
    args = ap.parse_args()
    return {"setup": cmd_setup, "sample": cmd_sample, "collect": cmd_collect}[args.cmd](
        args
    )


if __name__ == "__main__":
    raise SystemExit(main())
