"""Generate `docs/capability-matrix.md` from the solvers' `Capabilities` rows.

    python scripts/capability_matrix.py            # write the document
    python scripts/capability_matrix.py --check    # exit 1 if it has drifted

The rows are the source; this script only renders them, and
`tests/test_capability_matrix_doc.py` runs `--check` so a row edit that does
not regenerate the document fails CI rather than shipping a stale table.

Why generate rather than write it. momwire#396's registry exists so a consumer
stops keeping its own copy of what each family serves, and a hand-maintained
matrix document is exactly such a copy — the third one, after antennaknobs'
`_GROUND_EPS_SOLVERS` tuples and the per-solver docstrings. The document's
audience is a consumer designing around "what an engine is made of"
(antennaknobs#1006's engine picker), which is a question with one right answer
and it is in the rows.
"""

from __future__ import annotations

import argparse
import difflib
import pathlib
import sys

from momwire._capabilities import AXIS_VALUES, DERIVED_AXES, axes_for
from momwire.deck._solver import BASES, NEC2_BASES
from momwire.harrington import HarringtonSolver
from momwire.pulse import PulseSolver

from momwire import (
    ArrayBlockSolver,
    BSplineSolver,
    HMatrixSolver,
    RazorSolver,
    SinusoidalGalerkinSolver,
    SinusoidalSolver,
)

DOC = pathlib.Path(__file__).resolve().parent.parent / "docs" / "capability-matrix.md"

# Every class carrying a row, in the order the document reads best: the
# B-spline family and its two accelerators, the two sinusoidal rows, the
# razor-blade row, then the two reference rows. `PulseSolver` is last and is
# the only one no `--basis` name reaches (momwire#654 gave the pulse family
# one roster entry and it is the Harrington row).
CLASSES = (
    BSplineSolver,
    HMatrixSolver,
    ArrayBlockSolver,
    SinusoidalSolver,
    SinusoidalGalerkinSolver,
    RazorSolver,
    HarringtonSolver,
    PulseSolver,
)

# The eight declared booleans that are not geometry, in `_AXES` order —
# `centre_feeds` last because `_AXES` appends it (momwire#673); it was
# missing from this tuple until momwire#821 made the column load-bearing.
AXES = (
    "wire_loading",
    "extended_kernel",
    "junction_ports",
    "node_gaps",
    "knot_feeds",
    "per_wire_radius",
    "singular_enrichment",
    "centre_feeds",
)

# The ground column, plus the two geometry axes that only mean anything once
# there IS a ground. Free space is universal and not a cell.
GROUND_CELLS = ("pec", "refl-coef", "sommerfeld", "contact", "buried")

YES, NO = "yes", "**no**"


def _roster_names():
    """class -> the `--basis` names that resolve to it, with bound kwargs."""
    names = {}
    for name, (cls, kwargs) in BASES.items():
        spelt = name if not kwargs else f"{name} ({_kwargs_str(kwargs)})"
        names.setdefault(cls, []).append(spelt)
    return names


def _kwargs_str(kwargs):
    return ", ".join(f"{k}={v!r}" for k, v in sorted(kwargs.items()))


def _table(header, rows):
    widths = [max(len(str(r[i])) for r in [header, *rows]) for i in range(len(header))]
    out = ["| " + " | ".join(h.ljust(w) for h, w in zip(header, widths)) + " |"]
    out.append("| " + " | ".join("-" * w for w in widths) + " |")
    for row in rows:
        out.append(
            "| " + " | ".join(str(c).ljust(w) for c, w in zip(row, widths)) + " |"
        )
    return out


def _cell(caps, name):
    return YES if caps._served(name) else NO


def render() -> str:
    roster = _roster_names()
    lines = [
        "# The capability matrix",
        "",
        "**Generated** from each solver's `capabilities` class attribute by",
        "`scripts/capability_matrix.py`. Do not edit this file — edit the row and",
        "re-run `python scripts/capability_matrix.py`.",
        "`tests/test_capability_matrix_doc.py` runs the script's `--check` mode, so",
        "a row edit that skips the regeneration fails CI.",
        "",
        "A `Capabilities` row DESCRIBES; it enforces nothing. Every constructor and",
        "solve-time refusal named below stays the authoritative check, and",
        "`tests/test_refusals_are_declared.py` gates the direction that matters to a",
        "reader of this document: no solver may refuse a deck with a message this",
        "matrix would not have predicted.",
        "",
        "Free space is served by every row and is not a cell. `pec` is `ground_z`",
        "with no `ground_eps`; the other two grounds are `ground_model` values.",
        "",
        "## Roster names",
        "",
        "What a `--basis` name selects. Several names share one class, differing",
        "only in a bound keyword, so they share its row. The `nec2` column is",
        "`deck.NEC2_BASES`: the names the nec2 front door (`momwire.portal`, the",
        "`momwire-nec2c-*` commands) serves, which is exactly the `centre_feeds`",
        "column below — that dialect addresses segment centres, and a family",
        "that snaps to knots is refused there by name (momwire#821). The NEC-5",
        "dialect (`momwire.eznec`) addresses nodes and reads the whole roster.",
        "",
    ]
    lines += _table(
        ["`--basis`", "class", "bound", "`nec2`"],
        [
            [
                f"`{name}`",
                f"`{cls.__name__}`",
                f"`{_kwargs_str(kw)}`" if kw else "—",
                YES if name in NEC2_BASES else NO,
            ]
            for name, (cls, kw) in BASES.items()
        ],
    )
    lines += [
        "",
        "## Axes",
        "",
        "The eight declared booleans that describe the FORMULATION. Rows are",
        "classes, with the roster names that reach each one, because",
        "`HMatrixSolver` and `ArrayBlockSolver` are separate `--basis` entries",
        "over a row they inherit almost entirely from `BSplineSolver`.",
        "",
    ]
    lines += _table(
        ["class", "`--basis`", *(f"`{a}`" for a in AXES)],
        [
            [
                f"`{cls.__name__}`",
                ", ".join(f"`{n}`" for n in roster.get(cls, [])) or "—",
                *(_cell(cls.capabilities, a) for a in AXES),
            ]
            for cls in CLASSES
        ],
    )
    lines += [
        "",
        "## Grounds, contact and buried",
        "",
        "The ground column and the two GEOMETRY axes. `contact` is a wire END",
        "standing in the plane; `buried` is a wire wholly below it. Both are cells",
        "rather than condition tokens, so a row can refuse them outright — see",
        "`Capabilities`' docstring for the rule.",
        "",
        "A `yes` here is the cell alone. Combinations withdraw rungs from inside a",
        "served column — ground contact under `refl-coef` is refused by every row",
        "that serves both — and those are the `a+b` keys in the reasons below.",
        "",
    ]
    lines += _table(
        ["class", *(f"`{c}`" for c in GROUND_CELLS)],
        [
            [f"`{cls.__name__}`", *(_cell(cls.capabilities, c) for c in GROUND_CELLS)]
            for cls in CLASSES
        ],
    )

    # Every declared reason, once, with the cells that declare it. Deduplicated
    # because the tree deliberately shares sentences across rows — one message,
    # not a copy in each — and printing four identical paragraphs would hide
    # exactly the property the sharing exists for.
    # -- what each solver is MADE OF (antennaknobs#1006) ------------------
    #
    # The tables above say what a row SERVES. This one says what it is
    # composed of, which is the question a panel needs and the one the
    # roster names were silently carrying: `bspline` and `hmatrix` are
    # identical physics differing in assembly, `sinusoidal` and its Galerkin
    # sibling are one basis differing in testing, and nothing in either name
    # says so.
    #
    # Values come from `axes_for()` — declared union derived — never from the
    # booleans directly, so `ground_model` and `wire_position` are computed in
    # exactly one place for this document, its drift test and antennaknobs'
    # /capabilities alike.
    axis_names = list(AXIS_VALUES) + list(DERIVED_AXES)
    rows = []
    for cls in CLASSES:
        got = axes_for(cls.capabilities)
        cells = []
        for axis in axis_names:
            vals = got.get(axis)
            # A row that has not been described compositionally renders as an
            # explicit gap, never as an empty cell: "no axes declared" and "no
            # values on this axis" would otherwise look identical, and the
            # first is a row nobody has written while the second is a claim.
            cells.append("*not described*" if not vals else " / ".join(sorted(vals)))
        rows.append([f"`{cls.__name__}`", *cells])
    lines += [
        "",
        "## What each solver is made of",
        "",
        "The tables above are what a row SERVES. This is what it IS — the axes",
        "antennaknobs#1006 named, so a panel can show that `bspline` and",
        "`hmatrix` differ in assembly and nothing else, and that",
        "`sinusoidal-galerkin` differs from `sinusoidal` in the testing alone.",
        "",
        "**A cell lists every value the class can be configured to, not one",
        "value.** `degree=`, `nec5_quadrature=`, `extended_kernel=` and",
        "`feed_model=` are constructor keywords rather than separate classes, so",
        "one row is genuinely both `bspline-1` and `bspline-2`; a roster name is",
        "a saved preset picking one point in this space.",
        "",
        f"`{'` / `'.join(DERIVED_AXES)}` are DERIVED from `grounds` and",
        "`buried`/`contact` by `axes_for()` rather than restated per row, so",
        "they cannot drift from the cells above. `free` and `above` are",
        "universal on them for the same reason free space is not a ground cell.",
        "",
        "*not described* is a row carrying no compositional declaration at all —",
        "a gap, not a claim of emptiness.",
        "",
    ]
    lines += _table(["solver", *[f"`{a}`" for a in axis_names]], rows)

    sites: dict[str, list[str]] = {}
    for cls in CLASSES:
        for key, reason in sorted(cls.capabilities.refusals.items()):
            sites.setdefault(reason, []).append(f"`{cls.__name__}` `{key}`")
    lines += [
        "",
        "## The recorded reasons",
        "",
        f"{len(sites)} sentences across {sum(len(v) for v in sites.values())} "
        "declared cells, verbatim. A sentence shared by several rows is printed",
        "once and its sites listed: the tree keeps one message per refusal rather",
        "than a copy in each, and this is where that shows.",
        "",
        "These reach a user unchanged — as the exception a constructor raises, as",
        "the printout an EZNEC/NEC-2 seam writes, and as the text antennaknobs",
        "renders in host dialogs.",
        "",
    ]
    for reason in sorted(sites, key=lambda r: (sites[r][0], r)):
        lines.append("- " + ", ".join(sites[reason]))
        lines.append("")
        lines.append("  > " + reason)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--check",
        action="store_true",
        help="compare the committed document against the rows; do not write",
    )
    args = ap.parse_args(argv)
    text = render()
    if not args.check:
        DOC.write_text(text)
        print(f"wrote {DOC}")
        return 0
    current = DOC.read_text() if DOC.exists() else ""
    if current == text:
        print(f"{DOC.name} is up to date")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            text.splitlines(keepends=True),
            fromfile=f"{DOC.name} (committed)",
            tofile=f"{DOC.name} (from the rows)",
        )
    )
    print(
        "\ncapability-matrix.md has drifted from the declarations. "
        "Run: python scripts/capability_matrix.py",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
