"""Capture golden PyNEC impedances for the reflection-coefficient ground work.

Runs the validation matrix from docs/refl-coef-ground-plan.md against PyNEC
and regenerates tests/golden_refl_coef_ground.py as pure literals, so the
momwire test suite needs no PyNEC / antennaknobs dependency.

Must run under the antennaknobs venv (PyNEC + antennaknobs installed):

    /home/smburns/antennas/antennaknobs/.venv/bin/python \
        scripts/capture_refl_coef_ground_golden.py

Cases:
  - flat half-wave dipole (antennaknobs dipoles.invvee variant "dipole",
    28.47 MHz) at heights 0.05 / 0.1 / 0.2 / 0.35 / 0.5 wavelength;
  - inverted-L (verticals.inverted_l defaults, 28.57 MHz) with its radial
    counterpoise base at the same height fractions;
  - ground constants (eps_r, sigma): (10, 0.002), (13, 0.005), (3, 0.001).

Per case we record three PyNEC grounds:
  - "finite-fast": gn 0, reflection-coefficient approximation — the oracle
    the momwire implementation is judged against;
  - "finite": gn 2, Sommerfeld-Norton — secondary sanity, confirms we
    inherit gn 0's known low-height divergence rather than inventing our own;
  - "pec": PEC ground — the model momwire's grounded solve implements today,
    i.e. the error being fixed.
"""

import os
import sys

C_LIGHT = 299.792458  # MHz * m

HEIGHT_FRACS = (0.05, 0.1, 0.2, 0.35, 0.5)
GROUNDS = ((10.0, 0.002), (13.0, 0.005), (3.0, 0.001))
GROUND_MODELS = ("finite-fast", "finite", "pec")

OUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "tests",
    "golden_refl_coef_ground.py",
)


def _cases():
    from antennaknobs import resolve_variant_params
    from antennaknobs.designs.dipoles.invvee import Builder as InvVee
    from antennaknobs.designs.verticals.inverted_l import Builder as InvertedL

    for frac in HEIGHT_FRACS:
        params = dict(resolve_variant_params(InvVee, "dipole"))
        lam = C_LIGHT / params["design_freq"]
        params["base"] = frac * lam
        yield ("dipole", frac, params["design_freq"], InvVee(params))

    for frac in HEIGHT_FRACS:
        params = dict(InvertedL.default_params)
        lam = C_LIGHT / params["design_freq"]
        params["base"] = frac * lam
        yield ("inverted_l", frac, params["design_freq"], InvertedL(params))


def main():
    from antennaknobs.engines import PyNECEngine

    entries = []
    for name, frac, freq_mhz, builder in _cases():
        for eps_r, sigma in GROUNDS:
            row = {}
            for model in GROUND_MODELS:
                ground = "pec" if model == "pec" else (model, eps_r, sigma)
                z = PyNECEngine(builder, ground=ground).impedance()[0]
                row[model] = complex(z)
            entries.append((name, frac, eps_r, sigma, freq_mhz, row))
            print(
                f"{name:11s} h={frac:4.2f}wl eps={eps_r:4.1f} sig={sigma:5.3f}"
                f"  gn0={row['finite-fast']:.3f}  gn2={row['finite']:.3f}"
                f"  pec={row['pec']:.3f}"
            )

    lines = [
        '"""Golden PyNEC impedances for the reflection-coefficient ground work.',
        "",
        "GENERATED by scripts/capture_refl_coef_ground_golden.py — do not edit",
        "by hand; re-run that script (under the antennaknobs venv) to refresh.",
        "See docs/refl-coef-ground-plan.md for the validation matrix.",
        "",
        "GOLDEN maps (geometry, height_frac, eps_r, sigma) -> dict of ground",
        'model -> feed impedance in ohms. Ground models: "finite-fast" is NEC',
        "gn 0 (reflection-coefficient approximation, the oracle for momwire's",
        'ground_eps solve), "finite" is NEC gn 2 (Sommerfeld-Norton, secondary',
        'sanity), "pec" is the PEC ground momwire implements today. Geometries:',
        '"dipole" is the antennaknobs dipoles.invvee "dipole" variant at',
        '28.47 MHz with base = height_frac * wavelength; "inverted_l" is',
        "verticals.inverted_l defaults at 28.57 MHz, radial-counterpoise base",
        "at the same fractions.",
        '"""',
        "",
        "GOLDEN = {",
    ]
    for name, frac, eps_r, sigma, freq_mhz, row in entries:
        lines.append(f"    ({name!r}, {frac!r}, {eps_r!r}, {sigma!r}): {{")
        for model in GROUND_MODELS:
            lines.append(f"        {model!r}: {row[model]!r},")
        lines.append("    },")
    lines += [
        "}",
        "",
        "FREQ_MHZ = {'dipole': 28.47, 'inverted_l': 28.57}",
        "",
    ]
    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"\nwrote {OUT_PATH} ({len(entries)} cases)")


if __name__ == "__main__":
    sys.exit(main())
