"""Capture the momwire#935 SHAPE-CHECK deck against the NEC-5 binary, and
regenerate `tests/golden_grazing_shape_nec5.py`.

#935 lowered the below/below grazing floor from 0.1 deg to 0.05 deg. The gate
that shows this bought a real geometry rather than a lattice is a shallow
buried dipole: a 5.9114 m centre-fed dipole at 7.1 MHz over eps_r 13 /
sigma 0.005 S/m soil, laid flat at three depths.

The minimum pair angle on a flat wire is atan(2*depth / span), so the depth
maps straight onto the floor:

    depth      theta        old floor (0.1)   new floor (0.05)
    0.5 mm     0.00969 deg    refused           refused
    1.0 mm     0.01939 deg    refused           refused
    3.0 mm     0.05817 deg    refused           SERVED

So 3 mm is the case #935 buys, and the other two stay refused BY NAME -- the
gate asserts both halves, because a floor that quietly served everything would
pass a one-sided test just as well.

THE ORACLE IS LADDERED, NOT TRUSTED. NEC-5 is first order in the far mesh
(momwire#845) and its answer moves with feed grading (antennaknobs#1181), so
a single print is not a reference. Every wire is refined by the same factor
(x1, x2, x4, x8) on a uniform mesh -- no grading to hold fixed, no auto_mesh
in the way -- and the recorded value is the x8 print together with the
first-order Richardson limit z8 + (z8 - z4). The gap between them is the
oracle's own error bar and the gate's tolerance is set from it, not from a
round number. `scratch/931-study/probe_oracle_ladder.py` in antennaknobs is
where that ladder was first run.

Must run with the binary on `NEC5_EXE`:

    NEC5_EXE=~/antennas/NEC5-downloads/nec5-linux/nec5cl \
        .venv/bin/python scripts/capture_grazing_shape_nec5.py

Only the binary's PRINTED impedances are recorded; nothing about NEC-5's
internals is read, quoted or inferred here.
"""

from __future__ import annotations

import os
import re
import subprocess
import tempfile
from pathlib import Path

GOLDEN = Path(__file__).resolve().parents[1] / "tests" / "golden_grazing_shape_nec5.py"

# The deck. A centre gap of +-2.5 cm carries the source so the feed segment is
# the same physical size at every refinement; the arms are what the ladder
# refines. Radius 0.5 mm, well inside the thin-wire regime at 7.1 MHz.
HALF, GAP, RAD = 2.9557, 0.025, 5.0e-4
DEPTHS_MM = (0.5, 1.0, 3.0)
MULTS = (1, 2, 4, 8)
GN = "GN 0 0 0 0 1.300000E+01 5.000000E-03 1.000000E+00 0.000000E+00 NOFILE\n"
FR = "FR 0 1 0 0 7.100000E+00 0.000000E+00\n"


def deck(z, mult):
    """The cards at depth `z` (metres, negative) and refinement `mult`.

    `GE -1 0` is the documented ground card for a deck with buried wires and
    no ground contact (antennaknobs#1025): first field -1 is the unmodified
    expansion, second field 0 the default segment check.
    """
    n_arm, n_gap = 25 * mult, 2 * mult
    return (
        "CM momwire#935 grazing shape check\nCE\n"
        f"GW 1 {n_arm} {-HALF:.6E} 0. {z:.6E} {-GAP:.6E} 0. {z:.6E} {RAD:.6E}\n"
        f"GW 2 {n_gap} {-GAP:.6E} 0. {z:.6E} {GAP:.6E} 0. {z:.6E} {RAD:.6E}\n"
        f"GW 3 {n_arm} {GAP:.6E} 0. {z:.6E} {HALF:.6E} 0. {z:.6E} {RAD:.6E}\n"
        "GE -1 0\n" + GN + "EX 0 2 1 2 1.000000E+00 0.000000E+00\n" + FR + "XQ 0\nEN\n"
    )


def run(cards, exe):
    with tempfile.TemporaryDirectory(prefix="nec5_935_") as td:
        (Path(td) / "m.nec").write_text(cards)
        subprocess.run(
            [exe],
            input="m.nec\nm.out\n\n",
            text=True,
            capture_output=True,
            cwd=td,
            timeout=7200,
        )
        out = Path(td) / "m.out"
        text = out.read_text(errors="replace") if out.is_file() else ""
    m = re.search(
        r"- - - ANTENNA INPUT PARAMETERS - - -(.*?)(?:\n\s*\n\s*\n|$)", text, re.S
    )
    for line in m.group(1).splitlines() if m else []:
        t = line.split()
        if len(t) >= 12 and re.fullmatch(r"\d+", t[0]):
            return complex(float(t[7]), float(t[8]))
    raise RuntimeError("no ANTENNA INPUT PARAMETERS block in the printout")


def main():
    exe = os.environ.get("NEC5_EXE")
    if not exe:
        raise SystemExit("set NEC5_EXE to the nec5cl binary")
    rows = {}
    for mm in DEPTHS_MM:
        ladder = [run(deck(-mm / 1000.0, m), exe) for m in MULTS]
        rows[mm] = ladder
        z4, z8 = ladder[2], ladder[3]
        ext = z8 + (z8 - z4)
        print(
            f"{mm:5.2f} mm  x8 {z8.real:9.3f}{z8.imag:+9.3f}j   "
            f"Richardson {ext.real:9.3f}{ext.imag:+9.3f}j   "
            f"bar {abs(ext - z8):.4f} ohm"
        )

    body = [
        '"""NEC-5 printed impedances for the momwire#935 shape-check deck.',
        "",
        "GENERATED by scripts/capture_grazing_shape_nec5.py -- do not edit by",
        "hand. See that script for the cards, the depth/theta table and why the",
        "oracle is laddered rather than read once.",
        "",
        "Citation: NEC-5 (LLNL-CODE-746721), 5.9114 m centre-fed dipole buried",
        "0.5 / 1 / 3 mm in eps_r 13 / sigma 0.005 S/m soil at 7.1 MHz, uniform",
        "mesh refined x1/x2/x4/x8, 2026-09-06.",
        "",
        "`LADDER[depth_mm]` is the four printed impedances in refinement order;",
        "`CONVERGED[depth_mm]` is the first-order Richardson limit and",
        "`BAR[depth_mm]` the gap between it and the x8 print -- the oracle's own",
        "error bar, which is what the gate's tolerance is set from.",
        "",
        "No momwire float is recorded here on purpose: the momwire side is",
        "recomputed at test time.",
        '"""',
        "",
        "LADDER = {",
    ]
    for mm in DEPTHS_MM:
        # `repr` of a complex is already a valid, round-tripping literal
        # ("(175.69-6.617j)"). Hand-formatting the sign is how the #1199
        # generator produced output that ruff then reformatted, so the
        # emitter does not do it.
        vals = ", ".join(repr(z) for z in rows[mm])
        body.append(f"    {mm!r}: [{vals}],")
    body.append("}")
    body.append("")
    body.append("CONVERGED = {")
    for mm in DEPTHS_MM:
        z4, z8 = rows[mm][2], rows[mm][3]
        ext = z8 + (z8 - z4)
        body.append(f"    {mm!r}: {ext!r},")
    body.append("}")
    body.append("")
    body.append("BAR = {")
    for mm in DEPTHS_MM:
        z4, z8 = rows[mm][2], rows[mm][3]
        body.append(f"    {mm!r}: {abs((z8 + (z8 - z4)) - z8)!r},")
    body.append("}")
    GOLDEN.write_text("\n".join(body) + "\n")
    print(f"\nwrote {GOLDEN}")


if __name__ == "__main__":
    main()
