"""Capture the two momwire#567 ANCHOR decks against the NEC-5 binary, and
regenerate `tests/golden_buried_anchor_nec5.py`.

The anchors are the serve gates momwire#553 U5 banked for the
contact-plus-buried deck class it refuses (G-U5-12, and the deck-route twin
in `test_eznec_buried_refusal`): a 10 m ground-contact monopole fed at
segment 7 of 15 over (a) one detached 5 m radial 15 cm down and (b) a
four-radial fan, both over eps_r 13 / sigma 0.005 S/m soil at 7 MHz.

Until momwire#567 phase 0 the CARDS behind those numbers lived only in an
untracked scratch tree, and the phase-0 oracle run (issue #567, the phase-0
verdict comment) found the fan bank was a transcription 0.67 ohm off what
the engine actually prints — across eight deck spellings and GN0/GN2 alike.
This script is the durable home for both: the exact cards, the run recipe,
and the regeneration of the banked literals. The same run measured the
binary's buried-pair asymptotic workaround (`EZParam.txt`) at spread 0.0000
ohm on both decks, so the shipped configuration is captured with no
qualifier.

Must run under the antennaknobs venv (that is where the NEC-5 engine
wrapper lives), with the binary on `NEC5_EXE`:

    NEC5_EXE=~/antennas/NEC5-downloads/nec5-linux/nec5cl \
        /home/smburns/antennas/antennaknobs/.venv/bin/python \
        scripts/capture_buried_anchor_nec5.py

Only the binary's PRINTED impedances are recorded; nothing about NEC-5's
internals is read, quoted or inferred here.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

GOLDEN = Path(__file__).resolve().parents[1] / "tests" / "golden_buried_anchor_nec5.py"

# The cards, verbatim. These are the spellings the phase-0 oracle validated
# against the deck-route templates in `test_eznec_buried_refusal` (same
# geometry, same GE/GN/EX/PQ requests), kept as literals so a future session
# can re-run the engine without reconstructing a deck from test parameters.
ANCHOR_DECKS = {
    "lone-radial": (
        "CM momwire#567 anchor lone-radial\nCE\n"
        "GW 1,15,0.,0.,10.,0.,0.,0.,.001\n"
        "GW 2,10,0.,0.,-0.15,5.,0.,-0.15,.001\n"
        "GE 1,-1\nFR 0,1,0,0,7.\nGN 0,0,0,0,13.,.005\n"
        "EX 4,1,7,0,1.,0.\nPQ 0\nXQ 0\nEN\n"
    ),
    "four-radial": (
        "CM momwire#567 anchor four-radial\nCE\n"
        "GW 1,15,0.,0.,10.,0.,0.,0.,.001\n"
        "GW 2,10,0.,0.,-0.15,5.,0.,-0.15,.001\n"
        "GW 3,10,0.,0.,-0.15,0.,5.,-0.15,.001\n"
        "GW 4,10,0.,0.,-0.15,-5.,0.,-0.15,.001\n"
        "GW 5,10,0.,0.,-0.15,0.,-5.,-0.15,.001\n"
        "GE 1,-1\nFR 0,1,0,0,7.\nGN 0,0,0,0,13.,.005\n"
        "EX 4,1,7,0,1.,0.\nPQ 0\nXQ 0\nEN\n"
    ),
}


def main() -> None:
    from antennaknobs.engines.nec5 import NEC5Engine

    sys.path.insert(0, str(Path.home() / "antennas/antennaknobs/scripts"))
    from bench_nec5_walk_why import make_dipole

    captures = Path(
        os.environ.get("BURIED_ANCHOR_CAPTURES", "/tmp/buried-anchor-captures")
    )
    captures.mkdir(parents=True, exist_ok=True)
    eng = NEC5Engine(make_dipole(20), ground=None, capture_dir=captures)

    anchors: dict[str, complex] = {}
    for name, deck in ANCHOR_DECKS.items():
        z = complex(eng.run_deck(deck)[0][0][2])
        anchors[name] = z
        print(f"{name:>12}: nec5 prints {z:.4f}")

    _write_golden(anchors)


def _lit(z: complex) -> str:
    sign = "-" if z.imag < 0 else "+"
    return f"{z.real:.4f} {sign} {abs(z.imag):.4f}j"


def _write_golden(anchors: dict[str, complex]) -> None:
    lines = [
        '"""NEC-5 printed impedances for the two momwire#567 ANCHOR decks —',
        "the contact-plus-buried serve gates banked while the deck class",
        "refuses (momwire#553 U5, gated at G-U5-12 and the deck route).",
        "",
        "GENERATED by scripts/capture_buried_anchor_nec5.py — do not edit by",
        "hand. See that script for the cards, the run recipe and the fan",
        "re-bank story (the pre-phase-0 fan number was a transcription",
        "0.67 ohm off the engine's own printout). Citation: NEC-5",
        "(LLNL-CODE-746721), 10 m contact monopole over detached buried",
        "radials, eps_r 13 / sigma 0.005 S/m, 7 MHz, 2026-08-26.",
        "",
        "`ANCHOR_DECKS[name]` is the card text the binary ran, verbatim;",
        "`ANCHOR_LONE_RADIAL` / `ANCHOR_FOUR_RADIAL` are the impedances it",
        "PRINTED for them. The refusal prose in `_medium_spec` and",
        "`eznec/_serve` quotes these numbers; `test_buried_serve_553`'s",
        "G-U5-12 ties the spellings together and scores the decks the day",
        "the refusal lifts.",
        "",
        "No momwire float is recorded here on purpose: the momwire side is",
        "recomputed at test time. Pinning it would pin a cross-build float",
        "equality this tree does not have.",
        '"""',
        "",
        "ANCHOR_DECKS = {",
    ]
    for name, deck in ANCHOR_DECKS.items():
        lines.append(f'    "{name}": (')
        for card in deck.splitlines():
            lines.append(f'        "{card}\\n"')
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append(f"ANCHOR_LONE_RADIAL = {_lit(anchors['lone-radial'])}")
    lines.append(f"ANCHOR_FOUR_RADIAL = {_lit(anchors['four-radial'])}")
    GOLDEN.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {GOLDEN}")


if __name__ == "__main__":
    main()
