"""Pre-derive the same-edge static-kernel moment integrals J_pq with sympy
and dump them as inline numpy + C++ source.

The B-spline solver (`pysim.bspline.BSplinePySim`) needs closed-form
∫∫ (s-α)^p (s'-A)^q / √((s-s')²+a²) ds' ds for p, q ∈ {0..d} on every
same-edge segment pair. Sympy can integrate this in seconds, but doing so
at every module import is slow (8s+) and adds sympy as a runtime dep.

This script runs sympy ONCE and emits:
  * `src/pysim/_bspline_static_moments.py` — inline numpy expressions
    (CPU fallback when the C++ extension isn't available, and the
    canonical reference for the C++ side).
  * `src/pysim/_bspline_static_moments_inline.h` — inline C++ functions
    `J_static_pq_PP_QQ(alpha, beta, A, B, a)` for each (p, q). Included
    by `_accelerators.cpp` to power the static-moments fast path.

Re-run this script when you need to extend `max_d`.

Usage:
    .venv/bin/python scripts/derive_bspline_static_moments.py
"""

import pathlib

import sympy as sp
from sympy.printing.cxx import CXX11CodePrinter
from sympy.printing.numpy import NumPyPrinter

MAX_D = 2

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_PATH_PY = REPO_ROOT / "src" / "pysim" / "_bspline_static_moments.py"
OUT_PATH_H = REPO_ROOT / "src" / "pysim" / "_bspline_static_moments_inline.h"


def derive_all(max_d):
    s, sp_dummy, alpha, beta, A, B, a = sp.symbols(
        "s sp_dummy alpha beta A B a", real=True, positive=True
    )
    np_printer = NumPyPrinter()
    cxx_printer = CXX11CodePrinter()
    entries = []
    for p in range(max_d + 1):
        for q in range(max_d + 1):
            integrand = (
                (s - alpha) ** p
                * (sp_dummy - A) ** q
                / sp.sqrt((s - sp_dummy) ** 2 + a**2)
            )
            inner = sp.integrate(integrand, (sp_dummy, A, B))
            outer = sp.integrate(inner, (s, alpha, beta))
            np_code = np_printer.doprint(outer).replace("numpy.", "np.")
            cxx_code = cxx_printer.doprint(outer)
            entries.append((p, q, np_code, cxx_code))
    return entries


def emit_py(entries, path, max_d):
    body = [
        '"""Inline closed-form J_pq^static = ∫∫ (s-α)^p (s\'-A)^q / √((s-s\')²+a²)',
        f"on a single straight edge, for p, q ∈ {{0..{max_d}}}.",
        "",
        "Generated by scripts/derive_bspline_static_moments.py (do not edit).",
        '"""',
        "",
        "import numpy as np",
        "",
        "",
        "def J_static_moment(p, q, alpha, beta, A, B, a):",
        '    """One static moment integral (without the 1/(4π) prefactor).',
        "    alpha/beta/A/B/a broadcast as numpy arrays.",
        '    """',
    ]
    for idx, (p, q, np_code, _) in enumerate(entries):
        prefix = "if" if idx == 0 else "elif"
        body.append(f"    {prefix} (p, q) == ({p}, {q}):")
        body.append(f"        return {np_code}")
    body.append("    else:")
    body.append(
        f"        raise ValueError(f'(p, q) = ({{p}}, {{q}}) not in [0, {max_d}]²')"
    )
    body.append("")
    path.write_text("\n".join(body))


def emit_h(entries, path, max_d):
    body = [
        f"// Inline closed-form J_pq^static for p, q in {{0..{max_d}}}.",
        "// Generated by scripts/derive_bspline_static_moments.py (do not edit).",
        "// Included from _accelerators.cpp.",
        "#pragma once",
        "#include <cmath>",
        "",
    ]
    for p, q, _, cxx_code in entries:
        body.append(
            f"static inline double J_static_pq_{p}_{q}("
            "double alpha, double beta, double A, double B, double a) {"
        )
        body.append(f"    return {cxx_code};")
        body.append("}")
        body.append("")
    path.write_text("\n".join(body))


def main():
    print(f"Deriving J_pq^static for p, q ∈ {{0..{MAX_D}}} (this takes ~10s)…")
    entries = derive_all(MAX_D)
    emit_py(entries, OUT_PATH_PY, MAX_D)
    emit_h(entries, OUT_PATH_H, MAX_D)
    print(f"Wrote {OUT_PATH_PY}")
    print(f"Wrote {OUT_PATH_H}")


if __name__ == "__main__":
    main()
