"""Dump exact BSplineSolver inputs for the refl-coef ground validation matrix.

Uses antennaknobs' MomwireEngine wire translation (flat_wires_to_polylines +
bspline degree-2 segment parity) so the momwire-side solves in
scripts/compare_refl_coef_ground.py run the very same discretized geometry
antennaknobs will hand the solver in Phase 3. Regenerates
tests/fixtures_refl_coef_geoms.py as pure literals (no antennaknobs
dependency in the momwire suite).

Must run under the antennaknobs venv:

    /home/smburns/antennas/antennaknobs/.venv/bin/python \
        scripts/dump_refl_coef_geoms.py

Cases match scripts/capture_refl_coef_ground_golden.py (same builders, same
height fractions); ground plane sits at z=0 with the builder `base` param the
height above it.
"""

import os
import sys

C_LIGHT = 299.792458  # MHz * m

HEIGHT_FRACS = (0.02, 0.05, 0.1, 0.2, 0.35, 0.5)
YAGI_HEIGHT_FRACS = (0.2,)

OUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "tests",
    "fixtures_refl_coef_geoms.py",
)


def _cases():
    from antennaknobs import resolve_variant_params
    from antennaknobs.designs.beams.yagi import Builder as Yagi
    from antennaknobs.designs.dipoles.invvee import Builder as InvVee
    from antennaknobs.designs.verticals.inverted_l import Builder as InvertedL

    for frac in HEIGHT_FRACS:
        params = dict(resolve_variant_params(InvVee, "dipole"))
        lam = C_LIGHT / params["design_freq"]
        params["base"] = frac * lam
        yield ("dipole", frac, params["freq"], InvVee(params))

    for frac in HEIGHT_FRACS:
        params = dict(InvertedL.default_params)
        lam = C_LIGHT / params["design_freq"]
        params["base"] = frac * lam
        yield ("inverted_l", frac, params["freq"], InvertedL(params))

    for frac in YAGI_HEIGHT_FRACS:
        params = dict(Yagi.default_params)
        params["n_directors"] = 4
        lam = C_LIGHT / params["design_freq"]
        params["base"] = frac * lam
        yield ("yagi", frac, params["freq"], Yagi(params))


def main():
    from momwire import BSplineSolver

    from antennaknobs.engines.momwire import MomwireEngine

    entries = []
    for name, frac, freq_mhz, builder in _cases():
        eng = MomwireEngine(builder, solver=BSplineSolver, ground="pec")
        wavelength = 299792458.0 / (freq_mhz * 1e6)
        entries.append(
            (
                name,
                frac,
                {
                    "wires": [pl.tolist() for pl in eng._polylines],
                    "n_per_edge_per_wire": [list(e) for e in eng._edge_segments],
                    "feeds": [(w, arc, complex(v)) for w, arc, v in eng._feeds],
                    "junctions": eng._junctions or None,
                    "wire_radius": eng._wire_radius,
                    "wavelength": wavelength,
                },
            )
        )
        n_seg = sum(sum(e) for e in eng._edge_segments)
        print(
            f"{name:11s} h={frac:4.2f}wl  wires={len(eng._polylines)} "
            f"segs={n_seg} feeds={len(eng._feeds)} "
            f"junctions={len(eng._junctions or [])}"
        )

    lines = [
        '"""BSplineSolver inputs for the refl-coef ground validation matrix.',
        "",
        "GENERATED by scripts/dump_refl_coef_geoms.py — do not edit by hand;",
        "re-run that script (under the antennaknobs venv) to refresh. Same",
        "cases and keying as tests/golden_refl_coef_ground.py: GEOMS maps",
        "(geometry, height_frac) -> BSplineSolver kwargs (wires as nested",
        "lists; pass ground_z=0.0 to put the ground plane under them).",
        '"""',
        "",
        "GEOMS = {",
    ]
    for name, frac, kw in entries:
        lines.append(f"    ({name!r}, {frac!r}): {{")
        for key, val in kw.items():
            lines.append(f"        {key!r}: {val!r},")
        lines.append("    },")
    lines += ["}", ""]
    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"\nwrote {OUT_PATH} ({len(entries)} geometries)")


if __name__ == "__main__":
    sys.exit(main())
